### Categorias
POST http://localhost:9090/api/categoria/
Content-Type: application/json

{
  "nombre": "Bebida"
}

###
GET http://localhost:9090/api/categoria/
Accept: application/json

### Productos
POST http://localhost:9090/api/producto/
Content-Type: application/json

{
  "nombre": "Cerveza Stella 750ml",
  "CategoriaId": 1,
  "precio_venta": 17500
}

###
GET http://localhost:9090/api/producto/


### Cabecera Consumo
POST  http://localhost:9090/api/cabecera_consumo
Content-Type: application/json

{
  "MesaId": 3,
  "ClienteId": 1,
  "total": 0,
  "estado": "abierto"
}

###
GET http://localhost:9090/api/cabecera_consumo/


### Detalle Consumo
POST  http://localhost:9090/api/detalle_consumo/
Content-Type: application/json

{
  "ProductoId": 4,
  "CabeceraConsumoId": 6,
  "cantidad": 2
}

###
GET http://localhost:9090/api/detalle_consumo/



### Mesa
GET http://localhost:9090/api/mesa/2

###
PUT http://localhost:9090/api/cabecera_consumo/cerrar/?MesaId=2
Content-Type: application/json

{}


###
POST http://localhost:9090/api/mesa
Content-Type: application/json

{ "nombre": "Mesa 2", "RestauranteId": 1, "posicionx": 200, "posiciony": 100, "planta": 1, "capacidad": 4 }
